apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
data:
  config.yaml: |
    peers:
      - peer-address: 192.168.30.1
        peer-asn: 64512
        my-asn: 64512
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 192.168.69.0/24